<h3>
	Área Administrativa |
	<?php echo $this->tituloModelo;?>
</h3>


<!-- 
<div class="bs-callout bs-callout-danger">Nesta área é possível
	visualizar, verificar, buscar e adicionar novas Classes.</div>
-->

<div class="col-md-2 sidebar">
	<ul class="nav nav-sidebar">
		<li>
			<a href="<?php echo $this->baseUrl('/'.$this->controllerName);?>">Listar Todos</a>
		</li>
		
		<li>
			<a href="<?php echo $this->baseUrl('/'.$this->controllerName.'/adicionar');?>">Adicionar Novo</a>
		</li>
		<!-- 
		<li><a href="#">Relatórios</a>
		</li>
		 -->
	</ul>
</div>

<?php echo $this->flashMessages();?>

<div class="col-md-8 table-responsive">

	<?php if(count($this->lista)):?>
	<table class="table table-bordered table-hover table-striped table-responsive">
		<caption>Lista</caption>
				
		<thead>
			<tr>
				<th>Id</th>
				<th>Nome</th>
				<th>Professor</th>
				<th>Opções</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach($this->lista as $l):?>
			<tr>
				<td><?php echo $l['id'];?></td>
				<td><?php echo $l['nome'];?></td>
				<td><?php echo 'Ciclano';?></td>
				<td class="col-md-1" >
					<a href="<?php echo $this->baseUrl('/classe/editar/id/'.$l['id']);?>" >
						<span class="glyphicon glyphicon-pencil"></span>
						
					</a>
					<a href="<?php echo $this->baseUrl('/classe/remover/id/'.$l['id']);?>" >
						<span class="glyphicon glyphicon-trash"></span>

					</a>
				</td>
			</tr>
			<?php endforeach;?>
		</tbody>
		<tfoot>
			
		</tfoot>
	</table>
	<?php else:?>
		<p class="text-warning" >Nenhum dado foi encontrado.</p>
	<?php endif;?>
	

</div>
