<h3>Área Administrativa das Classes</h3>
<div class="bs-callout bs-callout-danger">Nesta área é possível
	visualizar, verificar, buscar e adicionar novas Classes.</div>

<div class="col-md-2 sidebar">
	<ul class="nav nav-sidebar">
		<li class="active"><a href="#">Listar Todos</a>
		</li>
		<li><a href="#">Adicionar Novo</a>
		</li>
		<li><a href="#">Relatórios</a>
		</li>
	</ul>
</div>
<div class="col-md-8">
	<table class="table table-bordered table-hover table-striped">
		<caption>Lista de Classes</caption>
		<thead>
			<tr>
				<th>#</th>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Username</th>
				<th>Opções</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>1</td>
				<td>Mark</td>
				<td>Otto</td>
				<td>@mdo</td>
				<td>
					<a href="#" class="" ><span class="glyphicon glyphicon-pencil"></span> Editar</a>
					<a href="#" class="" ><span class="glyphicon glyphicon-remove"></span> Excluir</a>
				</td>
			</tr>
			<tr>
				<td>2</td>
				<td>Jacob</td>
				<td>Thornton</td>
				<td>@fat</td>
			</tr>
			<tr>
				<td>3</td>
				<td>Larry</td>
				<td>the Bird</td>
				<td>@twitter</td>
			</tr>
		</tbody>
	</table>

</div>
