<?php echo $this->flashMessages();?>
<div class="col-md-8 table-responsive">

	<?php if(count($this->lista)):?>
	<table class="table table-bordered table-hover table-striped table-responsive">
		<caption>Lista</caption>
				
		<thead>
			<tr>
				<th>Id</th>
				<th>Nome</th>
				<th>Professor(es)</th>
				<th>Opções</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach($this->lista as $l):?>
			<tr>
				<td><?php echo $l['id'];?></td>
				<td><?php echo $l['nome'];?></td>
				<td>
					<?php 
						echo $l->professores;
					?>
				</td>
				<td class="col-md-1" >
					<a href="<?php echo $this->baseUrl('/classe/editar/id/'.$l['id']);?>" >
						<span class="glyphicon glyphicon-pencil"></span>
						
					</a>
					<a href="<?php echo $this->baseUrl('/classe/remover/id/'.$l['id']);?>" >
						<span class="glyphicon glyphicon-trash"></span>

					</a>
				</td>
			</tr>
			<?php endforeach;?>
		</tbody>
		<tfoot>
			
		</tfoot>
	</table>
	<?php else:?>
		<p class="text-warning" >Nenhum dado foi encontrado.</p>
	<?php endif;?>
	

</div>
