<div class="jumbotron">
	<h2 class="" >Olá [Usuário], Bem vindo ao Sistema Administrativo da IEBZonaSul!</h2>
	<p>This is a template for a simple marketing or informational website.
		It includes a large callout called a jumbotron and three supporting
		pieces of content. Use it as a starting point to create something more
		unique.</p>
	<p>
		<a href="#" class="btn btn-warning btn-lg" role="button">Leia a Documentação</a>
	</p>
</div>


