<?php echo $this->flashMessages();?>
<div class="col-md-8">
	<form class="form-inline" action="<?php echo $this->url(array('action'=>'upload')); ?>" method="POST" enctype="multipart/form-data" >
		
		<div class="form-group" >
			<label for="arquivo" class="form-label">Faça o upload do arquivo:</label>
			<div class="col-lg-12">
				<input id="arquivo" class="form-control" type="file" name="arquivo" />
			</div>			
		</div>

		<div class="form-group">
			<input class="btn btn-primary" type="submit" value="Enviar Arquivo" />
		</div>
	</form>
</div>
