<div class="text-center">
	<form class="form-signin" action="<?php echo $this->url(array('controller'=>'login','action'=>'logar'));?>" method="post" role="form">
		<h2 class="form-signin-heading">Bem vindo ao Sistema da IEB!</h2>
		<input type="text" name="usuario" class="form-control" placeholder="Usuário" required autofocus>
		<input type="password" name="senha" class="form-control" placeholder="Senha" required>
		<input type="submit" class="btn btn-lg btn-primary btn-block" type="submit" value="Entrar"/>
	</form>
</div>