<!DOCTYPE html>
<html lang="pt-br">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<link rel="shortcut icon"
	href="<?php echo $this->baseUrl();?>/public/bootstrap/ico/favicon.ico">


<title>Sistema Administrativo IEB</title>

<!-- Bootstrap core CSS -->
<link
	href="<?php echo $this->baseUrl();?>/public/bootstrap/css/bootstrap.min.css"
	rel="stylesheet">

<!-- Custom styles for this template -->
<link
	href="<?php echo $this->baseUrl();?>/public/bootstrap/css/navbar-static-top.css"
	rel="stylesheet" />

<!-- Flaty-Ui theme -->
<link
	href="<?php echo $this->baseUrl();?>/public/bootstrap/themes/flaty-ui.min.css"
	rel="stylesheet" />



<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="<?php echo $this->baseUrl();?>"> <span
					class="glyphicon glyphicon-home"></span> Sistema Administrativo </a>
			</div>
			<div class="navbar-collapse collapse">
			<?php echo $this->navigation(); ?>
			<ul class="nav navbar-nav navbar-right">
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo Zend_Auth::getInstance()->getIdentity()->nome;?> <b class="caret"></b></a>
		          <ul class="dropdown-menu">
		            <li><a href="<?php echo $this->url(array('controller'=>'login','action'=>'deslogar'));?>">Sair</a></li>
		          </ul>
		        </li>
		      </ul>
				<!-- 
				<ul class="nav navbar-nav">
					<li class="active"><a href="<?php echo $this->baseUrl();?>">Início</a>
					</li>
					<li><a href="#contact">Pessoas</a></li>
					<li class="dropdown"><a href="#" class="dropdown-toggle"
						data-toggle="dropdown">Dropdown <b class="caret"></b> </a>
						<ul class="dropdown-menu">
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li class="divider"></li>
							<li class="dropdown-header">Nav header</li>
							<li><a href="#">Separated link</a></li>
							<li><a href="#">One more separated link</a></li>
						</ul>
					</li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li><a href="../navbar/">Default</a></li>
					<li class="active"><a href="./">Static top</a></li>
					<li><a href="../navbar-fixed-top/">Fixed top</a></li>
				</ul>
				-->
			</div>
			<!--/.nav-collapse -->
		</div>
	</div>

	
	<div class="container">
	<?php if(Zend_Controller_Front::getInstance()->getRequest()->getControllerName()!='index'):?>
		<h3>
			Área Administrativa |
			<?php echo $this->tituloModelo; ?>
		</h3>

		<div class="col-md-2 sidebar">
			<ul class="nav nav-sidebar">
				<li><a href="<?php echo $this->url(array('action'=>'index'));?>">Listar
						Todos</a>
				</li>
				<li><a href="<?php echo $this->url(array('action'=>'adicionar'));?>">Adicionar
						Novo</a>
				</li>
				<!-- 
		<li><a href="#">Relatórios</a>
		</li>
		 -->
			</ul>
		</div>
	<?php endif;?>
		<?php echo $this->layout()->content; ?>
	</div>


	<div id="footer" class="">
		<div class="container">
			<p class="text-primary text-center">Todos direitos reservados &copy;.</p>
			<p class="text-primary text-center">Igreja Evangélica Batista Zona
				Sul.</p>
		</div>
	</div>


	<!-- Bootstrap core JavaScript
    ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script
		src="<?php echo $this->baseUrl();?>/public/js/libs/jquery-1.10.2.min.js"></script>
	<script
		src="<?php echo $this->baseUrl();?>/public/bootstrap/js/bootstrap.min.js"></script>
	<script
		src="<?php echo $this->baseUrl();?>/public/js/libs/jquery.validate.min.js"></script>
	<script
		src="<?php echo $this->baseUrl();?>/public/js/libs/jquery.maskedinput.min.js"></script>
	<script src="<?php echo $this->baseUrl();?>/public/js/main.js"></script>

</body>
</html>
