<!DOCTYPE html>
<html lang="pt-br">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<link rel="shortcut icon"
	href="<?php echo $this->baseUrl();?>/public/bootstrap/ico/favicon.ico">


<title>Login | Tela de Autenticação</title>

<!-- Bootstrap core CSS -->
<link
	href="<?php echo $this->baseUrl();?>/public/bootstrap/css/bootstrap.min.css"
	rel="stylesheet">

<!-- Custom styles for this template -->
<link
	href="<?php echo $this->baseUrl();?>/public/bootstrap/css/navbar-static-top.css"
	rel="stylesheet" />

<!-- Flaty-Ui theme -->
<link
	href="<?php echo $this->baseUrl();?>/public/bootstrap/themes/flaty-ui.min.css"
	rel="stylesheet" />

<link
	href="<?php echo $this->baseUrl();?>/public/bootstrap/themes/login.css"
	rel="stylesheet" />

<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
	
	<div class="container">
		<?php echo $this->layout()->content; ?>
	</div>


	<div id="footer" class="">
		<div class="container">
			<p class="text-primary text-center">Todos direitos reservados &copy;.</p>
			<p class="text-primary text-center">Igreja Evangélica Batista Zona
				Sul.</p>
		</div>
	</div>


	<!-- Bootstrap core JavaScript
    ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script
		src="<?php echo $this->baseUrl();?>/public/js/libs/jquery-1.10.2.min.js"></script>
	<script
		src="<?php echo $this->baseUrl();?>/public/bootstrap/js/bootstrap.min.js"></script>
	<script
		src="<?php echo $this->baseUrl();?>/public/js/libs/jquery.validate.min.js"></script>
	<script
		src="<?php echo $this->baseUrl();?>/public/js/libs/jquery.maskedinput.min.js"></script>
	<script src="<?php echo $this->baseUrl();?>/public/js/main.js"></script>

</body>
</html>
